/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
  'special' : IDL.Bool,
});
export const SeoMeta = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'keywords' : IDL.Text,
});
export const Page = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'seoMeta' : SeoMeta,
  'slug' : IDL.Text,
});
export const Time = IDL.Int;
export const Promotion = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : Time,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'image' : ExternalBlob,
  'startDate' : Time,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Int,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'hours' : IDL.Text,
  'whatsapp' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'mapUrl' : IDL.Text,
  'phone' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'contactInfo' : ContactInfo,
  'deliveryDetails' : IDL.Text,
  'customerPrincipal' : IDL.Text,
  'timestamp' : Time,
  'items' : IDL.Vec(MenuItem),
  'tableBookingDetails' : IDL.Text,
});
export const ExportData = IDL.Record({
  'promotions' : IDL.Vec(Promotion),
  'galleryImages' : IDL.Vec(GalleryImage),
  'contactInfo' : IDL.Opt(ContactInfo),
  'seoMeta' : IDL.Vec(IDL.Tuple(IDL.Text, SeoMeta)),
  'orders' : IDL.Vec(Order),
  'menuItems' : IDL.Vec(MenuItem),
  'pages' : IDL.Vec(Page),
  'testimonials' : IDL.Vec(Testimonial),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addMenuItem' : IDL.Func([MenuItem], [], []),
  'addPage' : IDL.Func([Page], [], []),
  'addPromotion' : IDL.Func([Promotion], [], []),
  'addTestimonial' : IDL.Func([Testimonial], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'exportData' : IDL.Func([], [ExportData], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getPage' : IDL.Func([IDL.Text], [IDL.Opt(Page)], ['query']),
  'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
  'getSeoMeta' : IDL.Func([IDL.Text], [IDL.Opt(SeoMeta)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([Order], [], []),
  'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
  'removeMenuItem' : IDL.Func([IDL.Text], [], []),
  'removePage' : IDL.Func([IDL.Text], [], []),
  'removePromotion' : IDL.Func([IDL.Text], [], []),
  'removeTestimonial' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateContactInfo' : IDL.Func([ContactInfo], [], []),
  'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updatePage' : IDL.Func([IDL.Text, Page], [], []),
  'updateSeoMeta' : IDL.Func([IDL.Text, SeoMeta], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
    'special' : IDL.Bool,
  });
  const SeoMeta = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'keywords' : IDL.Text,
  });
  const Page = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'seoMeta' : SeoMeta,
    'slug' : IDL.Text,
  });
  const Time = IDL.Int;
  const Promotion = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : Time,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'image' : ExternalBlob,
    'startDate' : Time,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Int,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'hours' : IDL.Text,
    'whatsapp' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'mapUrl' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'contactInfo' : ContactInfo,
    'deliveryDetails' : IDL.Text,
    'customerPrincipal' : IDL.Text,
    'timestamp' : Time,
    'items' : IDL.Vec(MenuItem),
    'tableBookingDetails' : IDL.Text,
  });
  const ExportData = IDL.Record({
    'promotions' : IDL.Vec(Promotion),
    'galleryImages' : IDL.Vec(GalleryImage),
    'contactInfo' : IDL.Opt(ContactInfo),
    'seoMeta' : IDL.Vec(IDL.Tuple(IDL.Text, SeoMeta)),
    'orders' : IDL.Vec(Order),
    'menuItems' : IDL.Vec(MenuItem),
    'pages' : IDL.Vec(Page),
    'testimonials' : IDL.Vec(Testimonial),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addMenuItem' : IDL.Func([MenuItem], [], []),
    'addPage' : IDL.Func([Page], [], []),
    'addPromotion' : IDL.Func([Promotion], [], []),
    'addTestimonial' : IDL.Func([Testimonial], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'exportData' : IDL.Func([], [ExportData], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllPages' : IDL.Func([], [IDL.Vec(Page)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactInfo' : IDL.Func([], [IDL.Opt(ContactInfo)], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getPage' : IDL.Func([IDL.Text], [IDL.Opt(Page)], ['query']),
    'getPromotions' : IDL.Func([], [IDL.Vec(Promotion)], ['query']),
    'getSeoMeta' : IDL.Func([IDL.Text], [IDL.Opt(SeoMeta)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([Order], [], []),
    'removeGalleryImage' : IDL.Func([IDL.Text], [], []),
    'removeMenuItem' : IDL.Func([IDL.Text], [], []),
    'removePage' : IDL.Func([IDL.Text], [], []),
    'removePromotion' : IDL.Func([IDL.Text], [], []),
    'removeTestimonial' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateContactInfo' : IDL.Func([ContactInfo], [], []),
    'updateMenuItem' : IDL.Func([IDL.Text, MenuItem], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updatePage' : IDL.Func([IDL.Text, Page], [], []),
    'updateSeoMeta' : IDL.Func([IDL.Text, SeoMeta], [], []),
  });
};

export const init = ({ IDL }) => { return []; };