/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactInfo {
  'hours' : string,
  'whatsapp' : string,
  'email' : string,
  'address' : string,
  'mapUrl' : string,
  'phone' : string,
}
export interface ExportData {
  'promotions' : Array<Promotion>,
  'galleryImages' : Array<GalleryImage>,
  'contactInfo' : [] | [ContactInfo],
  'seoMeta' : Array<[string, SeoMeta]>,
  'orders' : Array<Order>,
  'menuItems' : Array<MenuItem>,
  'pages' : Array<Page>,
  'testimonials' : Array<Testimonial>,
}
export type ExternalBlob = Uint8Array;
export interface GalleryImage {
  'id' : string,
  'blob' : ExternalBlob,
  'caption' : string,
  'category' : string,
}
export interface MenuItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
  'special' : boolean,
}
export interface Order {
  'id' : string,
  'status' : string,
  'contactInfo' : ContactInfo,
  'deliveryDetails' : string,
  'customerPrincipal' : string,
  'timestamp' : Time,
  'items' : Array<MenuItem>,
  'tableBookingDetails' : string,
}
export interface Page {
  'id' : string,
  'title' : string,
  'content' : string,
  'seoMeta' : SeoMeta,
  'slug' : string,
}
export interface Promotion {
  'id' : string,
  'title' : string,
  'endDate' : Time,
  'link' : string,
  'description' : string,
  'image' : ExternalBlob,
  'startDate' : Time,
}
export interface SeoMeta {
  'title' : string,
  'description' : string,
  'keywords' : string,
}
export interface Testimonial {
  'id' : string,
  'content' : string,
  'author' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addMenuItem' : ActorMethod<[MenuItem], undefined>,
  'addPage' : ActorMethod<[Page], undefined>,
  'addPromotion' : ActorMethod<[Promotion], undefined>,
  'addTestimonial' : ActorMethod<[Testimonial], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'exportData' : ActorMethod<[], ExportData>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllPages' : ActorMethod<[], Array<Page>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactInfo' : ActorMethod<[], [] | [ContactInfo]>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByCustomer' : ActorMethod<[string], Array<Order>>,
  'getPage' : ActorMethod<[string], [] | [Page]>,
  'getPromotions' : ActorMethod<[], Array<Promotion>>,
  'getSeoMeta' : ActorMethod<[string], [] | [SeoMeta]>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Order], undefined>,
  'removeGalleryImage' : ActorMethod<[string], undefined>,
  'removeMenuItem' : ActorMethod<[string], undefined>,
  'removePage' : ActorMethod<[string], undefined>,
  'removePromotion' : ActorMethod<[string], undefined>,
  'removeTestimonial' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateContactInfo' : ActorMethod<[ContactInfo], undefined>,
  'updateMenuItem' : ActorMethod<[string, MenuItem], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updatePage' : ActorMethod<[string, Page], undefined>,
  'updateSeoMeta' : ActorMethod<[string, SeoMeta], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];